variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_API_VERSION: "1.39"
  DATABRICKS_HOST: https://corning.cloud.databricks.com

services:
  - docker:dind

stages:
  - action

before_script:
    - ": \"${databricks_ci_token:?databricks_ci_token secret must be set and non-empty.}\""
    - git checkout -B "$CI_COMMIT_REF_NAME" "$CI_COMMIT_SHA"

GitHub onpush Action:
  image: dkamotsky/gitlab-actions:latest
  stage: action
  script:
    - act --list -P ubuntu-latest=dkamotsky/action:latest push
    - act -P ubuntu-latest=dkamotsky/action:latest -s DATABRICKS_HOST=$DATABRICKS_HOST -s DATABRICKS_TOKEN=$databricks_ci_token push
  rules:
    - if: '$CI_COMMIT_BRANCH'

GitHub onrelease Action:
  image: dkamotsky/gitlab-actions:latest
  stage: action
  script:
    - act --list -P ubuntu-latest=dkamotsky/action:latest release
    - act -P ubuntu-latest=dkamotsky/action:latest -s DATABRICKS_HOST=$DATABRICKS_HOST -s DATABRICKS_TOKEN=$databricks_ci_token release
  rules:
    - if: '$CI_COMMIT_TAG =~ /^release_.+/'
