name: Functional Test Pipeline

on: [push]

jobs:
  functional-tests:

    runs-on: ubuntu-latest

    env:
      MLFLOW_TRACKING_URI: 'databricks'
      DATABRICKS_HOST: {{ "${{ secrets.DATABRICKS_HOST }}" }}
      DATABRICKS_TOKEN: {{ "${{ secrets.DATABRICKS_TOKEN }}" }}

    steps:
      - uses: actions/checkout@v1

      - name: Announce
        run: |
          echo "Running ONPUSH GitHub Action"

      - name: Install pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -U tools/dbx-0.7.0-py3-none-any.whl

      - name: Test with the test script
        run: |
          ./tests/main.sh

      - name: Prepare profile
        run: |
          echo "[DEFAULT]" >> ~/.databrickscfg
          echo "host = $DATABRICKS_HOST" >> ~/.databrickscfg
          echo "token = $DATABRICKS_TOKEN" >> ~/.databrickscfg

      - name: Deploy functional test job
        run: |
          dbx deploy --jobs={{cookiecutter.corning_division.lower()}}_{{cookiecutter.project_slug}}_sample_func_test --requirements-file=conf/cloud-requirements.txt

      - name: Run functional test job
        run: |
          dbx launch --job={{cookiecutter.corning_division.lower()}}_{{cookiecutter.project_slug}}_sample_func_test --trace
