name: Release Pipeline

on:
  release:
    types:
      - created

jobs:
  release:

    runs-on: ubuntu-latest

    env:
      MLFLOW_TRACKING_URI: 'databricks'
      DATABRICKS_HOST: {{ "${{ secrets.DATABRICKS_HOST }}" }}
      DATABRICKS_TOKEN: {{ "${{ secrets.DATABRICKS_TOKEN }}" }}

    steps:
      - uses: actions/checkout@v1

      - name: Announce
        run: |
          echo "Running ONRELEASE GitHub Action"

      - name: Install pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dbx
        run: |
          pip install -U tools/dbx-0.7.0-py3-none-any.whl

      - name: Prepare profile
        run: |
          echo "[DEFAULT]" >> ~/.databrickscfg
          echo "host = $DATABRICKS_HOST" >> ~/.databrickscfg
          echo "token = $DATABRICKS_TOKEN" >> ~/.databrickscfg

      - name: Deploy acceptance tests
        # Job name must be defined in .dbx/deployment.json
        run: |
          dbx deploy --jobs=cicd_{{cookiecutter.corning_division.lower()}}_acc_test_{{cookiecutter.project_slug}}_sample --deployment-file=.dbx/deployment.json --requirements-file=.dbx/requirements.txt

      - name: Run acceptance tests
        # Job name must be defined in .dbx/deployment.json
        run: |
          dbx launch --job=cicd_{{cookiecutter.corning_division.lower()}}_acc_test_{{cookiecutter.project_slug}}_sample --trace --existing-runs=wait

      - name: Deploy the production job
        # Job name must be defined in .dbx/deployment.json
        run: |
          dbx deploy --jobs={{cookiecutter.corning_division.lower()}}_production_{{cookiecutter.project_slug}}_sample --deployment-file=.dbx/deployment.json --requirements-file=.dbx/requirements.txt
