name: Release Pipeline

on:
  release:
    types:
      - created

jobs:
  release:

    runs-on: ubuntu-latest

    env:
      MLFLOW_TRACKING_URI: 'databricks'
      DATABRICKS_HOST: ${{{{ secrets.DATABRICKS_HOST }}}}
      DATABRICKS_TOKEN: ${{{{ secrets.DATABRICKS_TOKEN }}}}

    steps:
      - uses: actions/checkout@v1

      - name: Announce
        run: |
          echo "Running ONRELEASE GitHub Action"

      - name: Install pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dbx
        run: |
          pip install -U tools/dbx-0.7.0-py3-none-any.whl

      - name: Prepare profile
        run: |
          echo "[{{cookiecutter.profile}}]" >> ~/.databrickscfg
          echo "host = $DATABRICKS_HOST" >> ~/.databrickscfg
          echo "token = $DATABRICKS_TOKEN" >> ~/.databrickscfg

      - name: Deploy acceptance tests
        run: |
          dbx deploy --jobs={{cookiecutter.project_slug}}-acc-test --requirements-file=cloud-requirements.txt

      - name: Run acceptance tests
        run: |
          dbx launch --job={{cookiecutter.project_slug}}-acc-test --trace

      - name: Deploy the production job
        run: |
          dbx deploy --jobs={{cookiecutter.project_slug}}-production --requirements-file=cloud-requirements.txt
