name: Python package

on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      MLFLOW_TRACKING_URI: 'databricks'
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    steps:
    - uses: actions/checkout@v1

    - name: Announce
      run: |
        echo "Running ONRELEASE GitHub Action"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install deployment/databrickslabs_cicdtemplates-0.2.3-py3-none-any.whl

    - name: Build artifact
      run: |
        python setup.py bdist_wheel

    - name: Deploy artifact
      run: |
        python -c "from databrickslabs_cicdtemplates import release_cicd_pipeline; release_cicd_pipeline.main('integration-tests', 'pipelines', True);"
