version: "3.8"

services:
  test:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: base
    entrypoint:
      - /{{cookiecutter.project_slug}}/tests/main.sh
    volumes:
     - ..:/{{cookiecutter.project_slug}}

