version: "3.8"

services:
  run:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: base
    entrypoint:
      - /{{cookiecutter.project_slug}}/docker/scripts/run_now.sh
    command:
      - $ARGS
    volumes:
     - ..:/{{cookiecutter.project_slug}}


